ALTER TABLE agent
    ADD COLUMN IF NOT EXISTS duration INT NOT NULL DEFAULT 0 AFTER status,
    ADD COLUMN IF NOT EXISTS old_time DATETIME NULL AFTER duration,
    ADD COLUMN IF NOT EXISTS old_status VARCHAR(30) NULL AFTER old_time,
    ADD COLUMN IF NOT EXISTS status_note TEXT NULL AFTER old_status;
